[build.environment]
  NODE_VERSION = "22"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  HUSKY = "0"

[build]
  publish = "dist"
  command = "pnpm install --no-frozen-lockfile && pnpm build"
